%Written by Darell 

% CONTRIBUTORS:
% Person1: Darell

% DOCUMENTATION:
% fs is the sampling frequency
% input is the signal input
% EQplot is the curve generated by the EQ in the app. it should look like /----\ when everthing is set to 1 


function output = Equalizer_Darell(input,EQplot,Fs)
%It's an EQ written by Darell
%   Split into frequencies and multiply by EQ 
    Mod_Freq = fftshift(fft(input));
    filtered_Mod_Freq = fftshift(Mod_Freq .* EQplot);
    output = real(ifft(filtered_Mod_Freq));
    %plot(output);
end

